services:
  barebones-react:
    image: node:current-alpine
    labels:
      lagoon.type: none
    volumes:
      - .:/app
    ports:
      - '3000:3000'
    command: sh -c "cd /app && npm install && npm run dev"
